name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-go@v6.5.0
        with:
          go-version: "1.25"

      - name: gofmt
        run: |
          diff <(gofmt -l .) <(echo -n)

      - name: go vet
        run: go vet ./...

      - name: go build
        run: go build ./...

      - name: go test
        run: go test ./...
